# syntax=toml
#
# Example configuration for Paneru.
#
[options]
# Enables focus follows mouse. Enabled by default, set to false to disable.
# focus_follows_mouse = true

# Enables mouse follows focus. Enabled by default, set to false to disable.
# mouse_follows_focus = true

mouse_resize_modifier = "cmd + shift"

# Array of widths used by the `window_resize` action to cycle between.
# Defaults to 25%, 33%, 50%, 66% and 75%.
preset_column_widths = [0.33, 0.50, 0.66, 0.75, 0.90]

# How many fingers to use for moving windows left and right.
# Make sure that it doesn't clash with OS setting for workspace switching.
# Values lower than 3 will be ignored.
# Remove the line to disable the gesture feature.
# Apple touchpads support gestures with more than five fingers (!),
# but it is probably not that useful to use two hands :)
# swipe_gesture_fingers = 4

# Swiping the windows left and right will keep sliding them until the first or
# last window. Set to false to always keep the current window on screen and
# fully exposed. Enabled by default.
# continuous_swipe = true

auto_center = true

# Window movement speed in pixels/second.
# To disable animations, leave this unset or set to a very large value.
animation_speed = 20


[bindings]
# Moves the focus between windows.
window_focus_west = "cmd - h"
window_focus_east = "cmd - l"
window_focus_north = "cmd - k"
window_focus_south = "cmd - j"

# Swaps windows in chosen direction.
window_swap_west = "alt - h"
window_swap_east = "alt - l"

# Jump to the left-most or right-most windows.
window_focus_first = "cmd + shift - h"
window_focus_last = "cmd + shift - l"

# Move the current window into the left-most or right-most positions.
window_swap_first = "alt + shift - h"
window_swap_last = "alt + shift - l"

# Centers the current window on screen.
window_center = "lalt - c"

# Cycles between the window sizes defined in the `preset_column_widths` option.
window_resize = "alt - r"

# Toggle full width for the current focused window.
window_fullwidth = "alt - f"

# Toggles the window for management. If unmanaged, the window will be "floating".
window_manage = "ctrl + alt - t"

# Stacks and unstacks a window into the left column. Each window gets a 1/N of the height.
window_stack = "alt - ]"
window_unstack = "alt + shift - ]"

# Moves currently focused window to another display.
window_nextdisplay = "alt - n"

# Quits the window manager.
quit = "ctrl + alt - q"

window_virtual_north = "cmd + shift - k"
window_virtual_south = "cmd + shift - j"
window_virtualmove_north = "cmd + alt - k"
window_virtualmove_south = "cmd + alt - j"
window_virtualnum_1 = "cmd + alt - 1"
window_virtualnum_2 = "cmd + alt - 2"
window_virtualnum_3 = "cmd + alt - 3"
window_virtualmovenum_1 = "cmd + alt + ctrl - 1"
window_virtualmovenum_2 = "cmd + alt + ctrl - 2"
window_virtualmovenum_3 = "cmd + alt + ctrl - 3"
window_virtualsendnum_1 = "cmd + alt + shift - 1"
window_virtualsendnum_2 = "cmd + alt + shift - 2"
window_virtualsendnum_3 = "cmd + alt + shift - 3"

# Window properties, matched by a RegExp title string.
[windows]

[windows.pip]
# Title RegExp pattern is required.
title = "Picture.*(in)?.*[Pp]icture"
# Do not manage this window, e.g. it will be floating.
floating = true

[windows.neovide]
# Matches an editor and always inserts its window at index 1.
title = ".*"
bundle_id = "com.neovide.neovide"
index = 1

[windows.all]
title = ".*"
horizontal_padding = 4

[padding]
top = 8
bottom = 8
left = 8
right = 8

[decorations.active.border]
radius = "auto"
enabled = true
color = "#89b4fa"
width = 2.0

[swipe.gesture]
fingers_count = 4
